-- Warehouse (cheap + safe)
CREATE WAREHOUSE IF NOT EXISTS WH_XS
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- DB + Schema
CREATE DATABASE IF NOT EXISTS SALES_FCST_DB;
CREATE SCHEMA IF NOT EXISTS SALES_FCST_DB.PUBLIC;

USE WAREHOUSE WH_XS;
USE DATABASE SALES_FCST_DB;
USE SCHEMA PUBLIC;