USE WAREHOUSE WH_XS;
USE DATABASE SALES_FCST_DB;
USE SCHEMA PUBLIC;

-- Feature store table
CREATE TABLE IF NOT EXISTS FEATURES (
  SERIES_ID STRING,
  DS DATE,
  Y FLOAT,
  LAG_1 FLOAT,
  LAG_7 FLOAT,
  ROLL7_MEAN FLOAT,
  ROLL28_MEAN FLOAT,
  DOW INT,
  IS_WEEKEND BOOLEAN,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Forecast output
CREATE TABLE IF NOT EXISTS FORECASTS (
  SERIES_ID STRING,
  DS DATE,
  YHAT FLOAT,
  MODEL_VERSION STRING,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Monitoring + backtest metrics
CREATE TABLE IF NOT EXISTS METRICS_MONITORING (
  RUN_ID STRING,
  SERIES_ID STRING,
  WINDOW_START DATE,
  WINDOW_END DATE,
  MAE FLOAT,
  MAPE FLOAT,
  MODEL_VERSION STRING,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
